/* eslint-disable no-unused-vars */
import React from 'react';

export const weatherWords = [
  'regnjacka',
  'paraply',
  'vinterjacka',
  'vantar',
  'mössa',
  'solglasögon',
  'badbyxor',
  'badmössa',
  'baddräkt',
  'solkräm',
  'solhatt',
  'regnhatt',
  'regnstövlar',
  'skidjacka',
  'skidbyxor',
  'skidglasögon',
  'skidhandskar',
  'regnställ',
  'skidmössa',
  'sandaler',
  'flip-flops',
  'regnrock',
  'skjorta',
  'kjol',
  'shorts',
  'tröja',
  'strumpor',
  'jeans',
  'regnbyxor',
  'kängor',
  'halsduk',
  'jacka',
  'skor',
  'huvtröja',
  't-shirt',
  'handskar',
  'vantar',
  'solbränna',
  'solnedgång'
];
